### ISSUE TITLE
email site

### ISSUE THREAD

**Issue by 1rods** [RezaSalaari/Instagram-Auto-Create-Account#1]
on the website: https://email-fake.com/ , it does not update when the bot tries to pull the verification code...
or the bot is still not doing it?
I tried to use it, but when it comes to verification it gives an error as if the bot couldn't find the code...
I think this site would be better for that: https://www.invertexto.com/gerador-email-temporario

**Comment by RezaSalaari** [comment]
Hi ,  The elements related to this site have changed and I haven't had the chance to edit again, unfortunately

If you want, you can make a pull request or wait to refactor codes again by me
